version: '3.4'

services:
  web:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000

  api:
    build:
      context: ./backend
      dockerfile: ./apps/api/Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3001:3001
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: ./apps/worker/Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: smartrr-cc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  postgres-data:
