version: '3.4'

services:
  web:
    build:
      context: ./frontend
      target: builder
    command: >
      npm run dev
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules

  api:
    build:
      context: ./backend
      dockerfile: ./apps/api/Dockerfile
      target: builder
    command: >
      npm run dev:api
    env_file:
      - ./backend/.env
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: ./apps/worker/Dockerfile
      target: builder
    command: >
      npm run dev:worker
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  postgres-data:
