version: '3.4'

services:
  web:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    environment:
      VITE_API_URL: http://localhost:3001
    depends_on:
      - api

  api:
    build:
      context: ./backend
      dockerfile: ./apps/api/Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3001:3001
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:docker@postgres:5432/smartrr-cc
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: ./apps/worker/Dockerfile
    volumes:
      - ./backend:/usr/src/app
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:docker@postgres:5432/smartrr-cc
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: smartrr-cc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker

  redis:
    image: redis

volumes:
  postgres-data:
