version: '3.1'

services:
  api:
    build:
      context: ./backend
      dockerfile: ./apps/api/Dockerfile
      target: development
    command: npm run start:dev api
    env_file:
      - ./backend/.env
    ports:
      - 3001:3001
    volumes:
      - ./backend:/usr/src/app
      # - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: ./apps/worker/Dockerfile
      target: development
    command: npm run start:dev worker
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
      # - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  postgres-data:
