version: '3.4'

services:
  # api:
  #   build:
  #     context: ./backend
  #     dockerfile: ./apps/api/Dockerfile
  #   env_file:
  #     - ./backend/.env
  #   ports:
  #     - 3001:3001
  #   volumes:
  #     - ./backend:/usr/src/app
  #   depends_on:
  #     - postgres
  #     - redis

  # worker:
  #   build:
  #     context: ./backend
  #     dockerfile: ./apps/worker/Dockerfile
  #   env_file:
  #     - ./backend/.env
  #   volumes:
  #     - ./backend:/usr/src/app
  #   depends_on:
  #     - postgres
  #     - redis

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  postgres-data:
